version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=monolito
      - POSTGRES_USER=monolito
      - POSTGRES_DB=monolito
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - net1
  
  videoflix:
    container_name: videoflix
    build: .
    restart: always
    environment:
      - PORT=5050
      - JWT_SECRET=aj1312afvfnbiobv
    ports:
      - 5050:5050
    command: yarn start
    networks:
      - net1

networks:
  net1:
    driver: bridge